legacy_layout=0
font_size_secondary=20

# CPU Stuff
cpu_text=R7 260
cpu_color=9E0808
cpu_stats
cpu_temp
cpu_power
cpu_mhz

ram
swap

# custom_text_center=

# GPU Stuff
gpu_text=RTX 5050
pci_dev=0000:01:00.0
gpu_stats
gpu_temp
gpu_power
gpu_mem_clock
gpu_core_clock
vram

custom_text_center=

# FPS Stuff
fps
fps_sampling_period=1000
frametime
frame_timing

gamemode

# Fan Stuff
custom_text=Fans
exec=echo "$(cat /sys/class/hwmon/hwmon7/fan1_input) / $(cat /sys/class/hwmon/hwmon7/fan2_input)"

background_alpha=0

toggle_hud=Shift_R+F12
