gamemode

# CPU Stuff
cpu_stats
cpu_temp
cpu_power
cpu_mhz

# GPU Stuff
pci_dev=0000:01:00.0
vram
gpu_stats
gpu_temp
gpu_power
gpu_mem_clock
gpu_core_clock

# FPS Stuff
fps
fps_sampling_period=1000
frametime
frame_timing

background_alpha=0

toggle_hud=Shift_R+F12