# Copy this file to ~/.config/wallust/wallust.toml to get started.
#
# Documentation: https://explosion-mental.codeberg.page/wallust/
# Man page:      man wallust.5

# ~ Backend ~
backend = "resized"

# ~ Palette ~
palette = "kmeans"

# ~ Style ~
style = "dark"

# ~ Salience options ~
salience = { sampling = "low", intensity = "vibrant" }

# ~ Kmeans options ~
kmeans = { k = 16, min_dist = 35.0 }

# ~ 16-color mode ~
use16cols = false

# ~ Contrast check ~
check_contrast = true

# ~ Saturation ~
saturation = 50

# ~ Alpha ~
alpha = 70

[templates]
qs    	   = { template = 'quickshell',    target = '~/.config/quickshell/Colors.qml' }
kitty      = { template = 'kitty',    target = '~/.config/theme/kitty.conf' }
waybar     = { template = 'WaybarCss',    target = '~/.config/theme/waybar.css' }
hypr 	   = { template = 'hypr', target = '~/.config/hypr/theme.lua'}
tofi 	   = { template = 'tofi', target = '~/.config/tofi/config'}
discord    = { template = 'discord', target = '~/.cache/hellwal/discord-colors.css'}

[hooks]
themecord = "themecord"
quickshell = "touch ~/.config/quickshell/shell.qml"

[templated_hooks]
