# wallpaper {
# 	monitor = eDp-1
# 	path = /mnt/General/Wallpaper/anime_girl.jpg
# 	fit_mode = cover
# }

splash = false

wallpaper {
    monitor = eDP-1
    path = /mnt/General/Wallpaper/goods/The_Crew_2_Artwork.jpeg
    fit_mode = cover
}

# wallpaper {
    # monitor = eDP-1
    # path = /mnt/General/Wallpaper/firewatch_sunset.jpg
    # fit_mode = cover
# }

# wallpaper {
#     monitor = 
#     path = ~/fallback.jxl
#     fit_mode = cover
# }
