wallpaper {
    monitor = eDP-1
 	# path = $HOME/Wallpapers/anime_girl.jpg
    path = $HOME/Wallpapers/goods/The_Crew_2_Artwork.jpeg
    # path = $HOME/Wallpapers/firewatch_sunset.jpg
    # path = $HOME/Wallpapers/goods/Diver_and_the_deep_Kraken.jpg
    # path = $HOME/Wallpapers/into_the_spider_verse.jpg
    fit_mode = cover
}




splash = false
