wallpaper {
    monitor = eDP-1
 	# path = /mnt/General/Wallpaper/anime_girl.jpg
    # path = /mnt/General/Wallpaper/goods/The_Crew_2_Artwork.jpeg
    # path = /mnt/General/Wallpaper/firewatch_sunset.jpg
    path = /mnt/General/Wallpaper/into_the_spider_verse.jpg
    fit_mode = cover
}




splash = false