hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })
hl.curve("slide",          { type = "bezier", points={{1, 0}, {0, 1}}})
hl.curve("overshoot",      { type = "bezier", points = { {0.5, 0.9}, {0.1, 1.1} } } )
hl.curve("rubber",         { type = "spring", mass = 1, stiffness = 70, dampening = 10 } )

hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })